### ISSUE TITLE
[Bug] I threw llamas into the void

### ISSUE THREAD

**Issue by Wpgradford** [ArshiaDPG/Llamarama#21]
**Describe the bug**
I threw some llama trader llamas into the void when he spawned in front of me and spooked me and it caused some world lag until I left the game

**To Reproduce**
I'm not sure exactly how to reproduce this, I tried spawning llamas and dropping them into the void in a different world and there wasn't any issue

**Game Instance Information:**
Minecraft 1.18.2, Llamarama 1.6.2

- Are there other mods in your instance?
I have about 300 other mods, but I'm not sure if they make a difference

**Crash Information(if relevant):**
- A crash log from when you got the issue:
Couldn't load chunk [47, 13]
java.lang.IllegalArgumentException: Data fixer not registered for: minecraft:DUMMY in block_entity
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at com.mojang.datafixers.schemas.Schema.getChoiceType(Schema.java:109)
	at net.minecraft.datafixer.schema.IdentifierNormalizingSchema.getChoiceType(IdentifierNormalizingSchema:52)
	at net.minecraft.datafixer.fix.ChoiceFix.makeRule(ChoiceFix:24)
	at com.mojang.datafixers.DataFix.getRule(DataFix.java:108)
	at com.mojang.datafixers.DataFixerUpper.lambda$getRule$6(DataFixerUpper.java:130)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap.computeIfAbsent(Long2ObjectOpenHashMap.java:499)
	at it.unimi.dsi.fastutil.longs.Long2ObjectMaps$SynchronizedMap.computeIfAbsent(Long2ObjectMaps.java:455)
	at com.mojang.datafixers.DataFixerUpper.getRule(DataFixerUpper.java:125)
	at com.mojang.datafixers.DataFixerUpper.update(DataFixerUpper.java:84)
	at net.minecraft.nbt.NbtHelper.update(NbtHelper:488)
	at net.minecraft.nbt.NbtHelper.update(NbtHelper:484)
	at net.minecraft.world.storage.VersionedChunkStorage.updateChunkNbt(VersionedChunkStorage:54)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.getUpdatedChunkNbt(ThreadedAnvilChunkStorage:969)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17256(ThreadedAnvilChunkStorage:601)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager:552)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131)
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager:561)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140)
	at net.minecraft.server.world.ServerChunkManager.getChunkBlocking(ServerChunkManager:1276)
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager:1172)
	at net.minecraft.world.World.getChunk(World:187)
	at net.minecraft.world.World.getChunk(World:4598)
	at net.minecraft.world.World.getBlockState(World:5090)
	at net.minecraft.entity.ai.pathing.MobNavigation.findPathTo(MobNavigation:43)
	at net.minecraft.entity.ai.pathing.EntityNavigation.findPathTo(EntityNavigation:120)
	at net.minecraft.entity.ai.pathing.EntityNavigation.startMovingTo(EntityNavigation:223)
	at io.github.llamarama.team.common.entity.ai.goal.CaravanGoal.tick(CaravanGoal.java:63)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.tick(PrioritizedGoal:65)
	at net.minecraft.entity.ai.goal.GoalSelector.tickGoals(GoalSelector:119)
	at net.minecraft.entity.ai.goal.GoalSelector.tick(GoalSelector:110)
	at net.minecraft.entity.mob.MobEntity.tickNewAi(MobEntity:742)
	at net.minecraft.entity.LivingEntity.tickMovement(LivingEntity:2609)
	at net.minecraft.entity.mob.MobEntity.tickMovement(MobEntity:546)
	at net.minecraft.entity.passive.PassiveEntity.tickMovement(PassiveEntity:127)
	at net.minecraft.entity.passive.AnimalEntity.tickMovement(AnimalEntity:58)
	at net.minecraft.entity.passive.HorseBaseEntity.tickMovement(HorseBaseEntity:553)
	at net.minecraft.entity.LivingEntity.tick(LivingEntity:2354)
	at net.minecraft.entity.mob.MobEntity.tick(MobEntity:346)
	at net.minecraft.entity.passive.HorseBaseEntity.tick(HorseBaseEntity:594)
	at io.github.llamarama.team.common.entity.woolyllama.WoollyLlamaEntity.tick(WoollyLlamaEntity.java:133)
	at io.github.llamarama.team.common.entity.mossyllama.MossyLlamaEntity.tick(MossyLlamaEntity.java:68)
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:702)
	at net.minecraft.world.World.tickEntity(World:485)
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:363)
	at net.minecraft.world.EntityList.forEach(EntityList:54)
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:331)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:907)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:851)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:97)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273)
	at java.lang.Thread.run(Thread.java:833)

**Comment by 0xJoeMama** [comment]
> caused some world lag

What is "world lag"?

**Comment by 0xJoeMama** [comment]
https://github.com/LlamaramaTeam/Llamarama/blob/37ce81767c8d2ff4785811115d68ab87f6279758/src/main/java/io/github/llamarama/team/common/entity/ai/goal/CaravanGoal.java#L63 

This is actually really weird, because I remember doing some in-world checks. Maybe I did them elsewhere. Yeah this needs to be addressed.

**Comment by Wpgradford** [comment]
I wasn't sure what to call it, it's the type of lag that your fps is fine but you can't break blocks and your character rubberbands. The time of day also was jumping back

**Comment by 0xmycf** [comment]
> https://github.com/LlamaramaTeam/Llamarama/blob/37ce81767c8d2ff4785811115d68ab87f6279758/src/main/java/io/github/llamarama/team/common/entity/ai/goal/CaravanGoal.java#L63 
> 
> 
> 
> This is actually really weird, because I remember doing some in-world checks. Maybe I did them elsewhere. Yeah this needs to be addressed.



What is it that needs to be addressed in this line?

**Comment by 0xJoeMama** [comment]
> What is it that needs to be addressed in this line?

Oh nothing, this line is causing the problem but we need to change the if statement in the beginning of the tick method. All I could piece together from the log is that the leashed llama died* right after the shouldContinue check and therefore tick couldnt locate the entity we are targetting for movement.

*Btw by died I mean was marked for removal, since that is what happens inside a tick. The entity is then removed in the next tick.

**Comment by 0xJoeMama** [comment]
Closing this since the issue I found was resolved. Thank you for reporting!
