### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by SalemRobin** [ArshiaDPG/Llamarama#42]
Server occasionally crashes. Here is the log.

[01:11:36] [Server thread/ERROR]: Exception stopping the server
net.minecraft.class_148: Saving entity NBT
        at net.minecraft.class_1297.method_5647(class_1297.java:1724) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5786(class_1297.java:1642) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5662(class_1297.java:1650) ~[server-intermediary.jar:?]
        at net.minecraft.class_5565.method_31734(class_5565.java:109) ~[server-intermediary.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.class_5565.method_31760(class_5565.java:107) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31812(class_5579.java:300) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31837(class_5579.java:317) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31842(class_5579.java:395) ~[server-intermediary.jar:?]
        at it.unimi.dsi.fastutil.longs.LongCollection.removeIf(LongCollection.java:285) ~[fastutil-8.5.6.jar:?]
        at net.minecraft.class_5579.method_31836(class_5579.java:393) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_14176(class_3218.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:527) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:593) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3782(class_3176.java:547) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "$$0" is null
        at net.minecraft.class_4844.method_26275(class_4844.java:33) ~[server-intermediary.jar:?]
        at net.minecraft.class_2512.method_25929(class_2512.java:185) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_25927(class_2487.java:210) ~[server-intermediary.jar:?]
        at io.github.llamarama.team.common.entity.caravantrader.CaravanTraderEntity.method_5652(CaravanTraderEntity.java:117) ~[Llamarama-1.8.1.jar:?]
        at net.minecraft.class_1297.method_5647(class_1297.java:1706) ~[server-intermediary.jar:?]
        ... 18 more

**Comment by 0xJoeMama** [comment]
Your bug report needs more information. In the future please use the bug report template that we provide.

Anyways, for now please tell me the llamarama version you are using and the minecraft version you are in.

**Comment by SalemRobin** [comment]
> 

1.19 Fabric, and the version I am using is 1.8.1.

It seems to me the server crashes whenever a caravan trader wants to spawn.

**Comment by 0xJoeMama** [comment]
When you say 1.19 you mean 1.19 exact or 1.19.x?

**Comment by SalemRobin** [comment]
> When you say 1.19 you mean 1.19 exact or 1.19.x?

1.19 exact.
